name       : python-ipdb
version    : 0.10.3
release    : 1
source     :
    - https://pypi.python.org/packages/ad/cc/0e7298e1fbf2efd52667c9354a12aa69fb6f796ce230cca03525051718ef/ipdb-0.10.3.tar.gz : 9ea256b4280fbe12840fb9dfc3ce498c6c6de03352eca293e4400b0dfbed2b28
license    : BSD-3-Clause
component  : programming.python
summary    : Integration of IPython pdb
description: |
    ipdb exports functions to access the IPython debugger, which features tab completion, syntax highlighting, better tracebacks, better introspection with the same interface as the pdb module.
builddeps  :
    - pkgconfig(python3)
    - python-ipython
    - python-setuptools
    - python3-ipython
rundeps    :
    - python-ipython
    - python3-ipython
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
