name       : python-ipdb
version    : 0.13.9
release    : 7
source     :
    - https://github.com/gotcha/ipdb/archive/refs/tags/0.13.9.tar.gz : 2935ef625bc25458b2829369dd8d6d3620a303efb100a605fa73790ca32f178b
license    : BSD-3-Clause
component  : programming.python
summary    : Integration of IPython pdb
description: |
    ipdb exports functions to access the IPython debugger, which features tab completion, syntax highlighting, better tracebacks, better introspection with the same interface as the pdb module.
builddeps  :
    - pkgconfig(python3)
    - python3-ipython
    - python-toml
rundeps    :
    - python3-ipython
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
